services:
  mysql:
    image: mysql:8.0.39-debian
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_USER: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tfg
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3308:3306